name: GraceReplica1
services:
  memgraph1:
    image: memgraph/memgraph:latest
    container_name: memgraph1
    command: ["--log-level=TRACE"]
    pull_policy: always
    volumes:
      - /Users/pandey/work/GRACE/PreloadData:/var/lib/memgraph/import
    healthcheck:
      test: ["CMD-SHELL", "echo 'RETURN 0;' | mgconsole || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 0s
    ports:
      - "7687:7687"
    networks:
      - Shared_net
  preload1:
    image: memgraph/memgraph:latest
    container_name: preload1
    depends_on:
      memgraph1:
        condition: service_healthy
    volumes:
      - /Users/pandey/work/GRACE/PreloadData:/var/lib/memgraph/import
    entrypoint:
      [
        "bash", "-c",
        "cat  /var/lib/memgraph/import/preloadMemgraph.cypher | mgconsole --host memgraph1 --port 7687"
      ]
    networks:
      - Shared_net
  lab1:
    image: memgraph/lab
    pull_policy: always
    container_name: lab1
    depends_on:
      memgraph1:
        condition: service_healthy
    ports:
      - "7474:3000"
    environment:
      QUICK_CONNECT_MG_HOST: memgraph1
      QUICK_CONNECT_MG_PORT: 7687
    networks:
      - Shared_net

  app1:
    build:
      context: ../
      dockerfile: ./gcpDockerfiles/GRACEDockerfile
    container_name: Grace1
    ports:
      - "3000:3000"
    environment:
      WS_URI: "ws://wsserver:1234"
      DATABASE_URI: bolt://memgraph1:7687
      NEO4J_USER: "pandey"
      NEO4J_PASSWORD: "verysecretpassword"
      USER: pandey
      DATABASE: MEMGRAPH
      LOG_LEVEL: error
      IS_PRELOAD_LEADER: Yes
    cap_add:
       - NET_ADMIN
    depends_on:
      memgraph1:
        condition: service_healthy
      preload1:
         condition: service_completed_successfully
    networks:
      - Shared_net
    volumes:
      - /Users/pandey/work/GRACE/PreloadData:/var/lib/grace/import
networks:
  Shared_net:
    external: true

